
services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DBURL: jdbc:postgresql://dpg-d3t1070dl3ps73b0mc7g-a.oregon-postgres.render.com/librarydatabase_jp8f
      DBNAME: librarydatabase_jp8f
      DBUSERNAME: librarydatabase_jp8f_user
      DBPASSWORD: gtSdse8Qhrj3hOYFDfmbT4EV6tLv5Cq8

