
services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d3t1070dl3ps73b0mc7g-a.oregon-postgres.render.com/librarydatabase_jp8f
      SPRING_DATASOURCE_USERNAME: librarydatabase_jp8f_user
      SPRING_DATASOURCE_PASSWORD: gtSdse8Qhrj3hOYFDfmbT4EV6tLv5Cq8
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
